#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
azure_yaml="$root/azure.yaml"
main_bicep="$root/infra/main.bicep"
resources_bicep="$root/infra/resources.bicep"

test -f "$azure_yaml"
test -f "$main_bicep"
test -f "$resources_bicep"

grep -Fqx 'name: agentic-engineering-workshop' "$azure_yaml"
grep -Fqx '  template: agentic-engineering-workshop@1.0.0' "$azure_yaml"
grep -Fq '    project: .' "$azure_yaml"
grep -Fq '    language: java' "$azure_yaml"
grep -Fq '    host: appservice' "$azure_yaml"
grep -Fq '    dist: target' "$azure_yaml"
grep -Fq '        shell: sh' "$azure_yaml"
grep -Fq '        run: ./mvnw -q -DskipTests package' "$azure_yaml"
grep -Fq '  provider: bicep' "$azure_yaml"
grep -Fq '  path: infra' "$azure_yaml"

grep -Fqx "targetScope = 'subscription'" "$main_bicep"
grep -Fq '@minLength(1)' "$main_bicep"
grep -Fq 'param environmentName string' "$main_bicep"
grep -Fq 'param location string' "$main_bicep"
grep -Fq "param modelName string = 'gpt-5.4-mini'" "$main_bicep"
grep -Fq "param modelVersion string = '2026-03-17'" "$main_bicep"
grep -Fq "param modelDeploymentName string = 'gpt-5-4-mini'" "$main_bicep"
grep -Fq "param modelDeploymentSku string = 'GlobalStandard'" "$main_bicep"
grep -Fq '@minValue(1)' "$main_bicep"
grep -Fq 'param modelDeploymentCapacity int = 10' "$main_bicep"
grep -Fq "'azd-env-name': environmentName" "$main_bicep"
grep -Fq "purpose: 'agentic-engineering-workshop'" "$main_bicep"
grep -Fq "var resourceGroupName = 'rg-\${environmentName}'" "$main_bicep"
grep -Fq "module resources 'resources.bicep'" "$main_bicep"
grep -Fq 'modelName: modelName' "$main_bicep"
grep -Fq 'modelVersion: modelVersion' "$main_bicep"
grep -Fq 'modelDeploymentName: modelDeploymentName' "$main_bicep"
grep -Fq 'modelDeploymentSku: modelDeploymentSku' "$main_bicep"
grep -Fq 'modelDeploymentCapacity: modelDeploymentCapacity' "$main_bicep"
grep -Fqx 'output AZURE_LOCATION string = location' "$main_bicep"
grep -Fqx 'output AZURE_RESOURCE_GROUP_NAME string = resourceGroup.name' "$main_bicep"
grep -Fqx 'output AZURE_SUBSCRIPTION_ID string = subscription().subscriptionId' "$main_bicep"
grep -Fqx 'output AZURE_TENANT_ID string = tenant().tenantId' "$main_bicep"
grep -Fqx 'output SERVICE_WEB_NAME string = resources.outputs.webAppName' "$main_bicep"
grep -Fqx 'output WEB_APP_URL string = resources.outputs.webAppUrl' "$main_bicep"
grep -Fqx 'output AZURE_OPENAI_ACCOUNT_NAME string = resources.outputs.foundryName' "$main_bicep"
grep -Fqx 'output AZURE_OPENAI_ENDPOINT string = resources.outputs.openAiEndpoint' "$main_bicep"
grep -Fqx 'output AZURE_OPENAI_DEPLOYMENT string = modelDeploymentName' "$main_bicep"
grep -Fqx 'output AZURE_OPENAI_MODEL string = modelName' "$main_bicep"
grep -Fqx 'output AZURE_OPENAI_MODEL_VERSION string = modelVersion' "$main_bicep"
grep -Fqx 'output AZURE_OPENAI_DEPLOYMENT_SKU string = modelDeploymentSku' "$main_bicep"
grep -Fqx 'output AZURE_OPENAI_DEPLOYMENT_CAPACITY int = modelDeploymentCapacity' "$main_bicep"

grep -Fq "resource appServicePlan 'Microsoft.Web/serverfarms@" "$resources_bicep"
grep -Fq "name: 'B1'" "$resources_bicep"
grep -Fq 'reserved: true' "$resources_bicep"
grep -Fq "resource foundry 'Microsoft.CognitiveServices/accounts@2025-06-01'" "$resources_bicep"
grep -Fq "kind: 'AIServices'" "$resources_bicep"
grep -Fq 'allowProjectManagement: true' "$resources_bicep"
grep -Fq 'customSubDomainName:' "$resources_bicep"
grep -Fq 'disableLocalAuth: true' "$resources_bicep"
grep -Fq "publicNetworkAccess: 'Enabled'" "$resources_bicep"
grep -Fq "resource modelDeployment 'Microsoft.CognitiveServices/accounts/deployments@" "$resources_bicep"
grep -Fq 'name: modelName' "$resources_bicep"
grep -Fq 'version: modelVersion' "$resources_bicep"
grep -Fq 'name: modelDeploymentSku' "$resources_bicep"
grep -Fq 'capacity: modelDeploymentCapacity' "$resources_bicep"
grep -Fq "resource web 'Microsoft.Web/sites@" "$resources_bicep"
grep -Fq "type: 'SystemAssigned'" "$resources_bicep"
grep -Fq "linuxFxVersion: 'JAVA|21-java21'" "$resources_bicep"
grep -Fq 'alwaysOn: true' "$resources_bicep"
grep -Fq "minTlsVersion: '1.2'" "$resources_bicep"
grep -Fq 'http20Enabled: true' "$resources_bicep"
grep -Fq "ftpsState: 'Disabled'" "$resources_bicep"
grep -Fq "name: 'AZURE_OPENAI_ENDPOINT'" "$resources_bicep"
grep -Fq "name: 'AZURE_OPENAI_MICROSOFT_FOUNDRY'" "$resources_bicep"
grep -Fq "value: 'true'" "$resources_bicep"
grep -Fq "name: 'AZURE_OPENAI_DEPLOYMENT'" "$resources_bicep"
grep -Fq 'value: modelDeploymentName' "$resources_bicep"
grep -Fq "name: 'AZURE_OPENAI_MODEL'" "$resources_bicep"
grep -Fq 'value: modelName' "$resources_bicep"
grep -Fq "value: '-Xms256m -Xmx1024m'" "$resources_bicep"
grep -Fq "value: '8080'" "$resources_bicep"
grep -Fq "'53ca6127-db72-4b80-b1b0-d745d6d5456d'" "$resources_bicep"
grep -Fq 'scope: foundry' "$resources_bicep"
grep -Fq 'guid(foundry.id, web.id, foundryUserRoleDefinitionId)' "$resources_bicep"

grep -Fqx 'output webAppName string = web.name' "$resources_bicep"
grep -Fqx "output webAppUrl string = 'https://\${web.properties.defaultHostName}'" "$resources_bicep"
grep -Fqx 'output foundryName string = foundry.name' "$resources_bicep"
grep -Fqx "output openAiEndpoint string = 'https://\${foundry.name}.openai.azure.com'" "$resources_bicep"

! grep -Rqi 'wayfinder-15\|prototype' "$azure_yaml" "$root/infra"

az bicep build --file "$main_bicep" --stdout >/dev/null
echo "workshop Azure infrastructure contract passed"
